### ISSUE TITLE
Encoding should be optional 

### ISSUE THREAD

**Issue by adamturski** [tylerhubert/rsql-criteria-typescript#19]
Encoding using encodingUri method should be optional and could be passed to the build method as an option. This would be good feature as it might not be desired to build e.g. filters which are already encoded.

**Comment by tylerhubert** [comment]
@adamturski,
Can you please check out the pending PR?  #20 

I've implemented option 1 that I laid out.  Basically still encode everything else besides the value that is passed in.  If that works for what you were asking for here, then I will go ahead and merge this and get a version created.  

These changes don't break anything because the default is to still encode the values that are passed in, so this is a safe change to make.

**Comment by adamturski** [comment]
@tylerhubert I was thinking that you can enable it or disable it during the build for whole string. I work in Angular project and in my case all parameters are encoded by default in Angular HttpClient, which leads to double encoding. As a workaround to my problem I simply decoded the output string from build method but then I found some problems that few characters were wrongly decoded especially >= was decoded to wrong value.
In my opinion it would be better to build the output as is and encode everything in the end as an option. What do you think about that?

**Comment by adamturski** [comment]
In my case numeric filter value was 205 and I used gte match mode which lead to generate:
amount%3E%3D205
after decoding using decodeURI()
amount%3E%253D205

Decoded value is wrong, because %3D was decoded to %253D.

**Comment by adamturski** [comment]
@tylerhubert I was able to solve my issue using decodeUriComponent() to decode output from build method, but it would be good to have an option to pass config to the build method in order to override few things, like encoding, quoting etc.

**Comment by tylerhubert** [comment]
@adamturski, I'm glad you were able to solve your issue using decodeUriComponent()!  I agree though that this isn't exactly a desirable solution.  In the PR, I've set up a RSQLBuilderOptions interface to allow for future expansion of options just like you said.

Thank you for more information about how this is being used.  I am also working in an Angular project and using the HttpClient, but I'm passing these strings down as query parameters instead of in the body of the request.  

I'll get the Pull Request updated to not encode anything in the outputted string so that we let Angular take care of it.  I'd like to keep the encoding at the individual levels instead of at the end because with the current setup each of the parts are useable outside of the overall builder.  And if we only do the encoding at the end, that wouldn't work to build up each of the different parts.

**Comment by tylerhubert** [comment]
I've updated the PR and README to provide examples of not encoding anything.  The build options will be passed down to all levels from wherever it is initially called from, so you should only have to pass that in once.  Examples are in the tests as well, but here is one:
```javascript
  it("should pass down the build options appropriately", () => {
    const criteria1 = new RSQLCriteria();
    criteria1.filters.and(
      new RSQLFilterBuilder()
        .column("foo")
        .equalTo("bar")
        .or()
        .column("bar")
        .equalTo("baz")
        .toList()
    );
    expect(criteria1.build()).toEqual(`$where=(foo=in=%22bar%22%20or%20bar=in=%22baz%22)`);
    expect(criteria1.build({ encodeString: false })).toEqual(
      `$where=(foo=in="bar" or bar=in="baz")`
    );
  });
```
Or specifically for GreaterThanEqualTo:
```javascript
  it('should build the proper string for the greaterThanOrEqualTo function', () => {
    const builder: RSQLFilter = new RSQLFilterBuilder();
    const list = builder.column('blah').greaterThanOrEqualTo('123').toList();
    expect(list.build()).toEqual(`blah${encodeURIComponent('>=')}123`);
    expect(list.build({encodeString: false})).toEqual(`blah>=123`);
  });
```

Let me know if this is looking better.

**Comment by tylerhubert** [comment]
Version 2.4.0 has been published to NPM with these changes.  If you find anything wrong, please reach out and we can get it fixed!
