### ISSUE TITLE
Operation EqualTo works uncorrect. You use =in= instead ==

### ISSUE THREAD

**Issue by mulatoschka1990** [tylerhubert/rsql-criteria-typescript#7]
https://github.com/tylerhubert/rsql-criteria-typescript/blob/15353bb682fb6e1fac41fa5fc034ea4ccafbf210/src/files/rsql-filter-expression.ts#L67

**Comment by tylerhubert** [comment]
Can you please give some more context on why this is causing a problem for you?

This change was intentional due to a problem that was found when working with https://github.com/tennaito/rsql-jpa on the backend.  It converts `==` into a SQL `LIKE` operation.  This causes problems when the search criteria contains a SQL wildcard in it.  To fix this, a one parameter `=in=` gets converted into an `=` in SQL, so I've changed the UI library over to handle that.

If you would like to continue having the front-end produce `==` syntax, the `like` function is available that does this.  https://github.com/tylerhubert/rsql-criteria-typescript/blob/master/src/files/rsql-filter-expression.ts#L73

This functionality is also noted in the README:
https://github.com/tylerhubert/rsql-criteria-typescript#a-note-on-function-names

If a change is needed we can look at making a change, but some more context would be appreciated to fully understand the problem.
